version: '3'
services:
  scheduler:
    hostname: scheduler
    image: daskdev/dask
    command: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    volumes:
      - /ymslanda:/ymslanda
  worker:
    hostname: worker-1
#    deploy:
#      mode: global
    image: daskdev/dask
    command: dask-worker scheduler:8786
    depends_on:
      - scheduler
    volumes:
      - /ymslanda:/ymslanda
